# version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - user-service
      - product-service
      - order-service
      - payment-service
    networks:
      - micro-net

  auth-service:
    build: ./auth-service
    container_name: auth-service
    expose:
      - "5000"
    networks:
      - micro-net

  user-service:
    build: ./user-service
    container_name: user-service
    expose:
      - "5000"
    networks:
      - micro-net

  product-service:
    build: ./product-service
    container_name: product-service
    expose:
      - "5000"
    networks:
      - micro-net

  order-service:
    build: ./order-service
    container_name: order-service
    expose:
      - "5000"
    environment:
      DB_HOST: order-db
      DB_NAME: orders_user
      DB_USER: orders_user
      DB_PASS: orders_pass
    depends_on:
      - order-db
    networks:
      - micro-net
  payment-service:
    build: ./payment-service
    container_name: payment-service
    expose:
      - "5000"
    networks:
      - micro-net

  order-db:
    image: postgres:16
    container_name: order-db
    environment:
      POSTGRES_DB: orders_user
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_pass
    volumes:
      - order_db_data:/var/lib/postgresql/data
      - ./order-db-services/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U orders_user" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - micro-net

volumes:
  order_db_data:


networks:
  micro-net:
    driver: bridge
